'''

THIS IS A CODE GENERATED BY
Cospy/cospy/equation_factory.py
DON'T MODIFY IT

'''

import logging
import numpy as np 
from numpy import exp, sin, cos, tan 

import pygsl._numobj as Numeric


class Problem(object):
    '''
    classdocs
    '''


    def __init__(self,params):
        '''
        Constructor
        '''
       
    def get_fields(self):
        return {'u': 'hyperbolic', 'v': 'hyperbolic'}
    

    def set_initial_data(self,grid):

        x, y, z = grid.get_coordinates()

        grid['u'] = self.id_u(x, y, z)

        grid['v'] = self.id_v()
        


    
    def id_u(self,x,y,z):

        return exp(-x**2-y**2+-z**2)
    
    def id_v(self):
        
        return 0
    


        
    def rhs(self,_t, _y, grid):
        
        
        grid.set_mol_fields(_y)
         
        rhs = dict()
                               
        rhs['u'] = self.rhs_u(grid['v'])        

        rhs['v'] = self.rhs_v(grid.lap('u'))        
        
        f = grid.get_rhs(rhs)
    
        return f.ravel()


    def rhs_v(self,Lap_u):
        return Lap_u

    def rhs_u(self,v):
        return v

    def rhs_jac(self,t, y, m):

        logging.error('rhs_jac not implemented')
        exit()

    def mg_problem(self):
        return dict()
        
    
    