'''

THIS IS A CODE GENERATED BY
Cospy/cospy/equation_factory.py
DON'T MODIFY IT

'''

import logging
import numpy as np 
from numpy import exp, sin, cos, tan 

import pygsl._numobj as Numeric


class Problem(object):
    '''
    classdocs
    '''


    def __init__(self):
        '''
        Constructor
        '''
       
    def get_fields(self):
        return {{field_dict}}
    

    def set_initial_data(self,grid):


        
        {% for field in field_map %}
        args=list()
        
        {% for arg in id_arg[field] %}
        args.append('{{arg}}')
        {% endfor %}
        
        grid.set_field('{{field}}', self.id_{{field}}, *args)
        {% endfor %}


    {% for field, id_f in id_dict.items() %}
    def id_{{field}}(self,{{field_dict[field]}}):
        return {{id_f}}
    {% endfor %}


        
    def rhs(self,_t, _y, grid):
        
        
        kwargs=dict()
        
        {% for field, rhs in rhs_dict.items() %}        
        kwargs['{{field}}'] = '{{rhs}}'
        {% endfor %}

        _f = grid.rhs(_y,**kwargs)        
    
        {% for field, condition in boundary_dict.items() %}        
        kwargs['{{field}}'] = '{{condition}}'
        {{boundary_condition}}
        {% endfor %}

        _f = grid.boundary(_y,_f,kwargs)

        return f



    def rhs_jac(self,t, y, m):

        logging.error('rhs_jac not implemented')
        exit()


    
    
    